//Using the fetch button to retrieve the posts
const fetchButton = document.getElementById("fetchButton");
fetchButton.addEventListener("click", function () { 
const loading = document.getElementById("loading");
loading.style.display="block";
fetch("https://jsonplaceholder.typicode.com/posts")
    .then(function(response) {
        console.log(response);
        return response.json();
    })

    .then(function (json) {
        console.log(json); //checking the JSON format in the console
        const div = document.getElementById("postList"); // grabbing the HTML element we want to interact with
        console.log(Array.isArray(json), typeof json[0]); //checking the object types
        let newHTML = ""; //establishing a blank string to insert HTML into
        
        //for each JSON element, add this addition to our string to post in the HTML
        json.forEach(function(json) {
            newHTML+= `
            <ul>
            <li><strong>userID:</strong> ${json.userId}</li>
            <li><strong>title:</strong> ${json.title}</li>
            <li><strong>body:</strong> ${json.body}</li>
        </ul>
        <br>
            `
        })
        div.innerHTML = newHTML; 
    })

    .catch(function (error) {
        console.error("Error fetching the data:", error);
        alert("There was an error retrieving the data");
    })

    .finally(() => {
        loading.style.display = "none";
    })
});

    //Use the fetch with a POST method to send form data as JSON to the API

    const postForm = document.getElementById("postForm"); //one global variable = the form

    postForm.addEventListener("submit", function(event) {
        event.preventDefault();
        const postData = {
            title: postForm.elements["titleInput"].value, //grabbing the inputted value from the Title of the form
            body: postForm.elements["bodyInput"].value, //grabbing the inputted value from the Body of the form
            userID: 1 //manually coding the user ID. the other ID will be generated by the back end.
        }
        console.log(postData);
        //adding an event listener to the form. The event listener is upon submission click,
        //and creates an object from the data in the form to post. This is important
        //because we can use it in the fetch to convert to JSON and send to the API.

        fetch("https://jsonplaceholder.typicode.com/posts", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(postData)
        })

        .then(response => {
            if(!response.ok) {
                throw new Error("HTTP error"); //tells us if the response from the API isn't okay
            }
            return response.json();
        })

        .then(JSONdata => {
            console.log("Server response:", JSONdata);
            alert(`We have received your data!`) //this logs our data to the console so we know it exists, and sends a confirmation to the user.
        }) //JSONdata is the object returned by the server. This should include the inputs plus an ID.

        .catch(error => {
            console.error("Error:", error); //throws a general error if there are network errors from fetch itself
        })

    })
